# Generated by Django 4.1.4 on 2022-12-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('necessity', models.BooleanField()),
                ('type', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='foodapp1.type')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('number', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='foodapp1.location')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp1.product')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('comment', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp1.product')),
            ],
        ),
    ]
