# Generated by Django 4.1.4 on 2022-12-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp1', '0002_product_purchase_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
