# Generated by Django 4.1.4 on 2022-12-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp1', '0005_alter_purchase_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
