# Generated by Django 4.1.4 on 2022-12-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp1', '0006_alter_purchase_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiration_date',
            field=models.DateField(blank=True, default='3030.01.01'),
        ),
    ]
