# Generated by Django 4.1.4 on 2022-12-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp1', '0011_alter_purchase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
    ]
