# Generated by Django 4.1.4 on 2022-12-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp1', '0012_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='foodapp1.location'),
        ),
    ]
