# Generated by Django 4.1.4 on 2022-12-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp1', '0014_alter_purchase_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
